#
# JBZoo Toolbox - Csv-Blueprint.
#
# This file is part of the JBZoo Toolbox project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @see        https://github.com/JBZoo/Csv-Blueprint
#

name: 'CSV Blueprint - Lint and validate by schemas'
description: 'Strict and flexible schema-based CSV file validation with the ability to report as GitHub Annotations in your PRs.'
author: 'Denis Smetannikov <admin@jbzoo.com>'

branding:
  icon: 'file-text'
  color: 'green'

inputs:
  csv:
    description: >
      Path(s) to validate. You can specify path in which CSV files will be searched.
      Feel free to use glob pattrens. Usage examples:
      /full/path/file.csv, p/file.csv, p/*.csv, p/**/*.csv, p/**/name-*.csv, **/*.csv, etc.
    required: true
  schema:
    description: 'Schema filepath. It can be a YAML, JSON or PHP. See examples on GitHub.'
    required: true
  report:
    description: 'Report format. Available options: text, table, github, gitlab, teamcity, junit.'
    default: table
    required: true
  quick:
    description: 'Quick mode. It will not validate all rows. It will stop after the first error.'
    default: no
    required: true
  skip-schema:
    description: 'Skip schema validation. If you are sure that the schema is correct, you can skip this check.'
    default: no
    required: true
  verbose:
    description: 'Verbosity level. Available options: `-v`, `-vv`, `-vvv`. And also there is option `--profile`.'
    default: -vv
    required: false
  extra:
    description: 'ANSI output. You can disable ANSI colors if you want with `--no-ansi`. Also see documentation on GitHub for other options.'
    default: "'--ansi' '--profile'"
    required: false

runs:
  using: 'docker'
  image: 'docker://jbzoo/csv-blueprint'
  env:
    GITHUB_ACTIONS: 'true'
  args:
    - validate:csv
    - --csv=${{ inputs.csv }}
    - --schema=${{ inputs.schema }}
    - --report=${{ inputs.report }}
    - --quick=${{ inputs.quick }}
    - --skip-schema=${{ inputs.skip-schema }}
    - ${{ inputs.verbose }}
    - ${{ inputs.extra }}
