#
# JBZoo Toolbox - Csv-Blueprint.
#
# This file is part of the JBZoo Toolbox project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @see        https://github.com/JBZoo/Csv-Blueprint
#

name: 'CSV Blueprint - Validator by schemas'
description: 'Strict and flexible schema-based CSV file validation with the ability to report as GitHub Annotations in your PRs.'
author: 'Denis Smetannikov <admin@jbzoo.com>'

branding:
  icon: 'file-text'
  color: 'green'

inputs:
  csv:
    description: >
      Path(s) to validate. You can specify path in which CSV files will be searched.
      Feel free to use glob pattrens. Usage examples:
      /full/path/file.csv, p/file.csv, p/*.csv, p/**/*.csv, p/**/name-*.csv, **/*.csv, etc.
    required: true
  schema:
    description: 'Schema filepath. It can be a YAML, JSON or PHP. See examples on GitHub.'
    required: true
  report:
    description: 'Report format. Available options: text, table, github, gitlab, teamcity, junit'
    default: github
    required: true
  quick:
    description: 'Quick mode. It will not validate all rows. It will stop after the first error.'
    default: no
    required: true

runs:
  using: 'docker'
  image: 'docker://jbzoo/csv-blueprint'
  args:
    - validate:csv
    - '--csv'
    - ${{ inputs.csv }}
    - '--schema'
    - ${{ inputs.schema }}
    - '--report'
    - ${{ inputs.report }}
    - '--quick'
    - ${{ inputs.quick }}
    - '--ansi'
    - '-vvv'
