#!/usr/bin/env php
<?php

declare(strict_types=1);

namespace JBZoo\CsvBlueprint;

use JBZoo\Cli\CliApplication;

\define('PATH_ROOT', __DIR__);

$vendorPaths = [
    __DIR__ . '/../../autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/vendor/autoload.php',
];

foreach ($vendorPaths as $file) {
    if (\file_exists($file)) {
        \define('JBZOO_AUTOLOAD_FILE', $file);
        break;
    }
}

require_once JBZOO_AUTOLOAD_FILE;

\date_default_timezone_set('UTC');

(new CliApplication('CSV Blueprint', '@git-version@'))
    ->registerCommandsByPath(PATH_ROOT . '/src/Commands', __NAMESPACE__)
    ->setLogo(
        <<<'EOF'
         _____            ______ _                       _       _   
        /  __ \           | ___ \ |                     (_)     | |  
        | /  \/_____   __ | |_/ / |_   _  ___ _ __  _ __ _ _ __ | |_ 
        | |   / __\ \ / / | ___ \ | | | |/ _ \ '_ \| '__| | '_ \| __|
        | \__/\__ \\ V /  | |_/ / | |_| |  __/ |_) | |  | | | | | |_ 
         \____/___/ \_/   \____/|_|\__,_|\___| .__/|_|  |_|_| |_|\__|
                                             | |                     
                                             |_|                     
        EOF,
    )
    ->run();
