#
# JBZoo Toolbox - Csv-Blueprint.
#
# This file is part of the JBZoo Toolbox project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @see        https://github.com/JBZoo/Csv-Blueprint
#

name: Stress Test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch Name'
        required: true
        default: 'master'
  pull_request:
    branches:
      - '*'
#  push:
#    branches:
#      - 'master'

jobs:
  docker-benchmark:
    name: via Docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ latest, local ]
        columns: [ 1, 5, 10, 20 ]
    env:
      BENCH_COLS: ${{ matrix.columns }}
      DOCKER_IMAGE: jbzoo/csv-blueprint:${{ matrix.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}

      - name: Build project # We need it to build benchmark tool. See ./tests/Benchmarks
        run: make build --no-print-directory

      - name: Building local image
        uses: docker/build-push-action@v5
        if: matrix.version == 'local'
        with:
          context: .
          push: false
          tags: ${{ env.DOCKER_IMAGE }}

      - name: Pulling latest image
        run: docker pull ${{ env.DOCKER_IMAGE }}
        if: matrix.version == 'latest'

      - name: 🔥 Benchmark 🔥
        run: make bench-create-csv bench-docker --no-print-directory


  php-benchmark:
    name: via PHP
    runs-on: ubuntu-latest
    strategy:
      matrix:
        columns: [ 1, 5, 10, 20 ]
    env:
      BENCH_COLS: ${{ matrix.columns }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          ini-values: opcache.enable_cli=1, opcache.jit=1255

      - name: Build project
        run: make build --no-print-directory

      - name: 🔥 Benchmark 🔥
        run: make bench-create-csv bench-php --no-print-directory
